# for task
task           = "predict"

# for model
model          = "unet"
num_hidden     = 64
num_layers     = 4
activation     = "relu"

# for equation
equation       = "heat"
d              = 2      # source component dimension
T              = 1.0    # prediction time

# for evaluation
sampler        = "sobol"
n_eval_spatial  = 10000

# for device
cuda            = true # use CPU
