
# for task
task           = "predict"
    
# for model 
model          = "fno"
num_hidden     = 64
num_layers     = 4
activation     = "relu"
    
# for equation
equation       = "wave"
T              = 5    # prediction time
    
# for evaluation
sampler        = "mesh"
batch_size     = 64
n_eval_sample  = 64
n_eval_spatial = 4096

# for device
cuda            = true # use CPU
    