# for task
task           = "varing"

# for model should retain the same as the saved weight
model          = "fno"
num_hidden     = 64
num_layers     = 4
activation     = "relu"

# for equation
equation       = "heat"
T              = 1.0    # prediction time

# for evaluation
sampler        = "sobol"
batch_size     = 16
n_eval_sample  = 16
n_eval_spatial = 16384

# for device
cuda            = true # use CPU
